# Generated by Django 6.0.2 on 2026-02-17 02:59

import ckeditor_uploader.fields
import django.db.models.deletion
import recipe_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=recipe_app.models.get_upload_path_category, verbose_name='Изображение')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Не отображать')),
            ],
            options={
                'verbose_name': 'Категория рецептов',
                'verbose_name_plural': 'Категории рецептов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название рецепта')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание рецепта')),
                ('cooking_steps', models.TextField(blank=True, null=True, verbose_name='Шаги приготовления')),
                ('cooking_time', models.TimeField(blank=True, null=True, verbose_name='Время приготовления ')),
                ('picture', models.ImageField(upload_to=recipe_app.models.get_upload_path, verbose_name='Изображение')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Не отображать')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.categoryrecipe', verbose_name='Категория рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
