# Generated by Django 4.0.6 on 2025-03-04 00:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import recipe_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=recipe_app.models.get_upload_path_category, verbose_name='Изображение')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Не отображать')),
            ],
            options={
                'verbose_name': 'Категория рецептов',
                'verbose_name_plural': 'Категории рецептов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название рецепта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание рецепта')),
                ('cooking_steps', models.TextField(blank=True, null=True, verbose_name='Шаги приготовления')),
                ('cooking_time', models.TimeField(blank=True, null=True, verbose_name='Время приготовления ')),
                ('picture', models.ImageField(upload_to=recipe_app.models.get_upload_path, verbose_name='Изображение')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Не отображать')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.categoryrecipe', verbose_name='Категория рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
