# Generated by Django 4.0.6 on 2025-03-17 05:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recipe_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание рецепта'),
        ),
    ]
